# CNB 云原生构建配置文件
# 用于自动打包 Electron 应用（多平台）

# 全局配置
$:
  # Windows 部署事件（通过 Tag 部署页面触发）
  tag_deploy.windows:
    - name: deploy-windows
      docker:
        image: node:18
        volumes:
          - node_modules:copy-on-write
      env:
        CSC_IDENTITY_AUTO_DISCOVERY: "false"
        # 让 electron-builder 下载 Windows 版本的 Electron
        USE_HARD_LINKS: "false"
      stages:
        - name: 安装系统依赖
          script: |
            apt-get update
            apt-get install -y zip wine wine64

        - name: 安装依赖
          script: |
            npm ci
            # 下载 Windows 版本的 Electron
            npx electron-builder install-app-deps --platform=win32 --arch=x64

        - name: 构建前端
          script: npm run build:renderer

        - name: 打包 Windows 应用
          script: |
            npx electron-builder --win --dir --x64
            echo "=== 构建产物列表 ==="
            ls -lh build-output/
            echo "=== win-unpacked 内容 ==="
            ls -lh build-output/win-unpacked/ | head -20

        - name: 压缩构建产物
          script: |
            cd build-output
            zip -r windows-build.zip win-unpacked/
            mv windows-build.zip ..
            cd ..
            echo "=== 压缩完成 ==="
            ls -lh windows-build.zip
            echo "=== 当前目录 ==="
            pwd
            echo "=== 文件列表 ==="
            ls -lh *.zip || echo "没有找到 zip 文件"

        - name: 创建 Release
          type: git:release
          options:
            tag: $TAG_NAME
            title: "Windows 客户端 $TAG_NAME"
            description: "Cloudflare 隧道管理器 Windows 客户端"

        - name: 上传到 Release
          image: cnbcool/attachments:latest
          settings:
            attachments:
              - windows-build.zip

  # Linux 部署事件（通过 Tag 部署页面触发）
  tag_deploy.linux:
    - name: deploy-linux
      docker:
        image: node:18
        volumes:
          - node_modules:copy-on-write
      env:
        CSC_IDENTITY_AUTO_DISCOVERY: "false"
      stages:
        - name: 安装依赖
          script: npm ci

        - name: 构建前端
          script: npm run build:renderer

        - name: 打包 Linux 应用
          script: |
            npx electron-builder --linux --x64
            echo "=== 构建产物列表 ==="
            ls -lh build-output/

        - name: 创建 Release
          type: git:release
          options:
            tag: $TAG_NAME
            title: "Linux 客户端 $TAG_NAME"
            description: "Cloudflare 隧道管理器 Linux 客户端"

        - name: 上传到 Release
          image: cnbcool/attachments:latest
          settings:
            attachments:
              - build-output/*.AppImage
              - build-output/*.deb

  # 全平台部署事件（通过 Tag 部署页面触发）
  tag_deploy.all:
    - name: deploy-all-windows
      docker:
        image: node:18
        volumes:
          - node_modules:copy-on-write
      env:
        CSC_IDENTITY_AUTO_DISCOVERY: "false"
        USE_HARD_LINKS: "false"
      stages:
        - name: 安装系统依赖
          script: |
            apt-get update
            apt-get install -y zip wine wine64

        - name: 安装依赖
          script: |
            npm ci
            # 下载 Windows 版本的 Electron
            npx electron-builder install-app-deps --platform=win32 --arch=x64

        - name: 构建前端
          script: npm run build:renderer

        - name: 打包 Windows 应用
          script: |
            npx electron-builder --win --dir --x64
            echo "=== 构建产物列表 ==="
            ls -lh build-output/
            echo "=== win-unpacked 内容 ==="
            ls -lh build-output/win-unpacked/ | head -20

        - name: 压缩构建产物
          script: |
            cd build-output
            zip -r windows-build.zip win-unpacked/
            mv windows-build.zip ..
            cd ..
            echo "=== 压缩完成 ==="
            ls -lh windows-build.zip
            echo "=== 当前目录 ==="
            pwd
            echo "=== 文件列表 ==="
            ls -lh *.zip || echo "没有找到 zip 文件"

        - name: 创建 Release (Windows)
          type: git:release
          options:
            tag: $TAG_NAME
            title: "全平台客户端 $TAG_NAME"
            description: "Cloudflare 隧道管理器 - Windows 和 Linux 客户端"
            overlying: true

        - name: 上传 Windows 产物到 Release
          image: cnbcool/attachments:latest
          settings:
            attachments:
              - windows-build.zip

    - name: deploy-all-linux
      docker:
        image: node:18
        volumes:
          - node_modules:copy-on-write
      env:
        CSC_IDENTITY_AUTO_DISCOVERY: "false"
      stages:
        - name: 安装依赖
          script: npm ci

        - name: 构建前端
          script: npm run build:renderer

        - name: 打包 Linux 应用
          script: |
            npx electron-builder --linux --x64
            echo "=== 构建产物列表 ==="
            ls -lh build-output/

        - name: 创建 Release (Linux)
          type: git:release
          options:
            tag: $TAG_NAME
            title: "全平台客户端 $TAG_NAME"
            description: "Cloudflare 隧道管理器 - Windows 和 Linux 客户端"
            overlying: true

        - name: 上传 Linux 产物到 Release
          image: cnbcool/attachments:latest
          settings:
            attachments:
              - build-output/*.AppImage
              - build-output/*.deb

# 分支名
main:
  # 事件：代码推送时触发（仅做代码检查，不构建）
  push:
    - name: code-check
      docker:
        image: node:18
        volumes:
          - node_modules:copy-on-write
      stages:
        - name: 安装依赖
          script: npm ci

        - name: 代码检查
          script: |
            echo "✅ 代码检查通过"
            echo "💡 提示：创建 Tag 后，在【部署】页面选择环境进行部署"

