name: Build and Release

on:
  push:
    tags:
      - 'v*'  # 当推送 v* 标签时触发（如 v1.0.0, v2.0.0）
  workflow_dispatch:  # 允许手动触发

jobs:
  build:
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [windows-latest]  # 可以添加 macos-latest, ubuntu-latest
    
    steps:
      - name: 检出代码
        uses: actions/checkout@v4
      
      - name: 设置 Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: 安装依赖
        run: npm ci
      
      - name: 构建前端
        run: npm run build:renderer
      
      - name: 构建主进程
        run: npm run build:main
        env:
          CSC_IDENTITY_AUTO_DISCOVERY: false  # 禁用代码签名
      
      - name: 打包应用
        run: npm run pack
        env:
          CSC_IDENTITY_AUTO_DISCOVERY: false
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: 上传构建产物
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ matrix.os }}
          path: |
            build-output/*.exe
            build-output/*.zip
            build-output/*.dmg
            build-output/*.AppImage
            build-output/*.deb
            build-output/*.rpm
          retention-days: 7
      
      - name: 创建 Release（仅标签触发）
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: |
            build-output/*.exe
            build-output/*.zip
            build-output/*.dmg
            build-output/*.AppImage
            build-output/*.deb
            build-output/*.rpm
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

