name: Build and Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-windows:
    runs-on: windows-latest
    timeout-minutes: 30

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build renderer
        run: npm run build:renderer

      - name: Build Windows app
        run: |
          echo "=== Building Windows app with icon ==="
          echo "Icon file exists:"
          if (Test-Path "assets/icons/icon.ico") {
            Write-Host "✓ Icon file found" -ForegroundColor Green
            Get-Item "assets/icons/icon.ico" | Select-Object Name, Length
          } else {
            Write-Host "✗ Icon file NOT found" -ForegroundColor Red
          }
          npx electron-builder --win --x64
        env:
          CSC_IDENTITY_AUTO_DISCOVERY: false
          DEBUG: electron-builder

      - name: List build output
        run: |
          echo "=== Build output ==="
          dir build-output
          echo "=== win-unpacked content ==="
          dir build-output\win-unpacked
          echo "=== Checking EXE files ==="
          Get-ChildItem "build-output\win-unpacked" -Filter "*.exe" | ForEach-Object {
            Write-Host "Found EXE: $($_.Name)" -ForegroundColor Green
            Write-Host "  Size: $([math]::Round($_.Length / 1MB, 2)) MB"
          }
          echo "=== Checking if Cloudflare隧道管理器.exe exists ==="
          if (Test-Path "build-output\win-unpacked\Cloudflare隧道管理器.exe") {
            Write-Host "✓ Cloudflare隧道管理器.exe found" -ForegroundColor Green
          } else {
            Write-Host "✗ EXE file NOT found" -ForegroundColor Red
          }

      - name: Force embed icon using rcedit
        run: |
          echo "=== Installing rcedit ==="
          npm install -g rcedit
          echo "=== Embedding icon into EXE ==="
          $exePath = "build-output\win-unpacked\Cloudflare隧道管理器.exe"
          $iconPath = "assets\icons\icon.ico"
          if (Test-Path $exePath) {
            rcedit $exePath --set-icon $iconPath
            Write-Host "✓ Icon embedded successfully" -ForegroundColor Green
          } else {
            Write-Host "✗ EXE file not found, cannot embed icon" -ForegroundColor Red
          }

      - name: Compress Windows build
        run: |
          cd build-output\win-unpacked
          Compress-Archive -Path * -DestinationPath ..\..\CFT_windows_x64.zip

      - name: Upload Windows artifact
        uses: actions/upload-artifact@v4
        with:
          name: CFT_windows_x64
          path: CFT_windows_x64.zip
          retention-days: 7

  build-linux:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build renderer
        run: npm run build:renderer

      - name: Build Linux app
        run: npx electron-builder --linux --x64
        env:
          CSC_IDENTITY_AUTO_DISCOVERY: false

      - name: List build output
        run: |
          echo "=== Build output ==="
          ls -lh build-output/

      - name: Rename Linux artifacts
        run: |
          cd build-output
          # Rename AppImage
          if ls *.AppImage 1> /dev/null 2>&1; then
            for file in *.AppImage; do
              mv "$file" "CFT_linux_x64.AppImage"
              echo "✓ Renamed to CFT_linux_x64.AppImage"
            done
          fi
          # Rename deb
          if ls *.deb 1> /dev/null 2>&1; then
            for file in *.deb; do
              mv "$file" "CFT_linux_x64.deb"
              echo "✓ Renamed to CFT_linux_x64.deb"
            done
          fi
          ls -lh

      - name: Upload Linux artifacts
        uses: actions/upload-artifact@v4
        with:
          name: CFT_linux_x64
          path: |
            build-output/CFT_linux_x64.AppImage
            build-output/CFT_linux_x64.deb
          retention-days: 7

  build-macos:
    runs-on: macos-latest
    timeout-minutes: 30
    strategy:
      matrix:
        arch: [x64, arm64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build renderer
        run: npm run build:renderer

      - name: Create macOS icon from PNG
        run: |
          echo "=== Creating .icns file from PNG ==="
          mkdir -p icon.iconset
          # Create different sizes for iconset
          sips -z 16 16     assets/icons/icon.png --out icon.iconset/icon_16x16.png
          sips -z 32 32     assets/icons/icon.png --out icon.iconset/icon_16x16@2x.png
          sips -z 32 32     assets/icons/icon.png --out icon.iconset/icon_32x32.png
          sips -z 64 64     assets/icons/icon.png --out icon.iconset/icon_32x32@2x.png
          sips -z 128 128   assets/icons/icon.png --out icon.iconset/icon_128x128.png
          sips -z 256 256   assets/icons/icon.png --out icon.iconset/icon_128x128@2x.png
          sips -z 256 256   assets/icons/icon.png --out icon.iconset/icon_256x256.png
          sips -z 512 512   assets/icons/icon.png --out icon.iconset/icon_256x256@2x.png
          sips -z 512 512   assets/icons/icon.png --out icon.iconset/icon_512x512.png
          sips -z 1024 1024 assets/icons/icon.png --out icon.iconset/icon_512x512@2x.png
          # Convert to icns
          iconutil -c icns icon.iconset -o assets/icons/icon.icns
          echo "✓ Created icon.icns"
          ls -lh assets/icons/icon.icns

      - name: Build macOS app
        run: npx electron-builder --mac --${{ matrix.arch }}
        env:
          CSC_IDENTITY_AUTO_DISCOVERY: false

      - name: List build output
        run: |
          echo "=== Build output ==="
          ls -lh build-output/

      - name: Rename macOS artifacts
        run: |
          cd build-output
          # Rename DMG
          if ls *.dmg 1> /dev/null 2>&1; then
            for file in *.dmg; do
              mv "$file" "CFT_macos_${{ matrix.arch }}.dmg"
              echo "✓ Renamed to CFT_macos_${{ matrix.arch }}.dmg"
            done
          fi
          ls -lh

      - name: Upload macOS artifact
        uses: actions/upload-artifact@v4
        with:
          name: CFT_macos_${{ matrix.arch }}
          path: build-output/CFT_macos_${{ matrix.arch }}.dmg
          retention-days: 7

  release:
    needs: [build-windows, build-linux, build-macos]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')

    steps:
      - name: Download Windows artifact
        uses: actions/download-artifact@v4
        with:
          name: CFT_windows_x64

      - name: Download Linux artifact
        uses: actions/download-artifact@v4
        with:
          name: CFT_linux_x64

      - name: Download macOS x64 artifact
        uses: actions/download-artifact@v4
        with:
          name: CFT_macos_x64

      - name: Download macOS arm64 artifact
        uses: actions/download-artifact@v4
        with:
          name: CFT_macos_arm64

      - name: List downloaded files
        run: |
          echo "=== Downloaded artifacts ==="
          ls -lh

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            CFT_windows_x64.zip
            CFT_linux_x64.AppImage
            CFT_linux_x64.deb
            CFT_macos_x64.dmg
            CFT_macos_arm64.dmg
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

